/**
 * Created by Sonphil on 26-03-21.
 */

object Version {
    const val AppCompat = "1.3.1"
    const val Browser = "1.3.0"
    const val Compose = "1.0.0"
    const val ConstraintLayout = "2.0.4"
    const val CoreKtx = "1.6.0"
    const val Coroutines = "1.5.0"
    const val Firebase = "28.2.0"
    const val FirebaseGradle = "2.7.1"
    const val Fragment = "1.3.5"
    const val Glide = "4.12.0"
    const val GoogleServices = "4.3.8"
    const val Gradle = "7.0.0"
    const val GradleVersions = "0.39.0"
    const val Hilt = "2.38.1"
    const val HiltAndroid = "1.0.0"
    const val JUnit = "4.13.2"
    const val Kotlin = "1.5.10"
    const val KtlintGradle = "10.1.0"
    const val LeakCanary = "2.7"
    const val Lifecycle = "2.3.1"
    const val LifecycleExtensions = "2.2.0"
    const val LifecycleViewModelKtx = "2.3.1"
    const val MaterialComponents = "1.4.0"
    const val MockK = "1.12.0"
    const val Moshi = "1.12.0"
    const val Navigation = "2.3.5"
    const val Preference = "1.1.1"
    const val RecyclerViewAnimators = "4.0.2"
    const val Retrofit = "2.9.0"
    const val Room = "2.3.0"
    const val SwipeRefreshLayout = "1.1.0"
    const val TestCore = "1.4.0"
    const val Tosty = "1.5.0"
    const val UltraViewPager = "1.0.7.8@aar"
    const val WorkManager = "2.5.0"
}