name: Android CI

on:
  push:
    branches:
      - '*'

jobs:
  debug_apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Lint Check
      run: bash ./gradlew ktlintCheck
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload debug APK
      uses: actions/upload-artifact@v1
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
